import './style.scss'
import './scripts/garage/count-cars'
import './scripts/api'
import './scripts/ui'
import './scripts/draw-pages'
import './scripts/garage/create-car'
import './scripts/garage/update-car'
import './scripts/garage/remove-car'
import './scripts/garage/generate-cars'
import './scripts/garage/pagination'
import './scripts/garage/animation'
import './scripts/winners/count-winners'
import './scripts/winners/draw-winners'
import './scripts/garage/car-utils'

